BEGIN;

CREATE TABLE IF NOT EXISTS public.wuwa_rebuild_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL DEFAULT 0,
    locked_bitmap BIGINT NOT NULL DEFAULT 0,
    locked_count INTEGER NOT NULL DEFAULT 0,

    original_stat1 BIGINT NOT NULL DEFAULT 0,
    original_stat2 BIGINT NOT NULL DEFAULT 0,
    original_stat3 BIGINT NOT NULL DEFAULT 0,
    original_stat4 BIGINT NOT NULL DEFAULT 0,
    original_stat5 BIGINT NOT NULL DEFAULT 0,
    original_stat_all BIGINT NOT NULL DEFAULT 0,
    o1_desc TEXT NOT NULL DEFAULT '',
    o2_desc TEXT NOT NULL DEFAULT '',
    o3_desc TEXT NOT NULL DEFAULT '',
    o4_desc TEXT NOT NULL DEFAULT '',
    o5_desc TEXT NOT NULL DEFAULT '',

    new_stat1 BIGINT NOT NULL DEFAULT 0,
    new_stat2 BIGINT NOT NULL DEFAULT 0,
    new_stat3 BIGINT NOT NULL DEFAULT 0,
    new_stat4 BIGINT NOT NULL DEFAULT 0,
    new_stat5 BIGINT NOT NULL DEFAULT 0,
    new_stat_all BIGINT NOT NULL DEFAULT 0,
    n1_desc TEXT NOT NULL DEFAULT '',
    n2_desc TEXT NOT NULL DEFAULT '',
    n3_desc TEXT NOT NULL DEFAULT '',
    n4_desc TEXT NOT NULL DEFAULT '',
    n5_desc TEXT NOT NULL DEFAULT '',

    source_image TEXT NOT NULL DEFAULT '',
    uploaded_image TEXT NOT NULL DEFAULT '',
    uploader_nickname TEXT NOT NULL DEFAULT '',
    uploader_email TEXT NOT NULL DEFAULT '',
    uploader_wechat TEXT NOT NULL DEFAULT '',
    uploader_qq TEXT NOT NULL DEFAULT '',
    request_ip TEXT NOT NULL DEFAULT '',
    raw_json JSONB,
    deleted INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT wuwa_rebuild_log_deleted_check CHECK (deleted IN (0, 1))
);

COMMENT ON TABLE public.wuwa_rebuild_log IS '鸣潮声骸重构识别记录';
COMMENT ON COLUMN public.wuwa_rebuild_log.user_id IS '用户 ID';
COMMENT ON COLUMN public.wuwa_rebuild_log.locked_bitmap IS '原词条锁定位图';
COMMENT ON COLUMN public.wuwa_rebuild_log.original_stat1 IS '原词条第 1 项 bitmap';
COMMENT ON COLUMN public.wuwa_rebuild_log.original_stat2 IS '原词条第 2 项 bitmap';
COMMENT ON COLUMN public.wuwa_rebuild_log.original_stat3 IS '原词条第 3 项 bitmap';
COMMENT ON COLUMN public.wuwa_rebuild_log.original_stat4 IS '原词条第 4 项 bitmap';
COMMENT ON COLUMN public.wuwa_rebuild_log.original_stat5 IS '原词条第 5 项 bitmap';
COMMENT ON COLUMN public.wuwa_rebuild_log.original_stat_all IS '原词条合集 bitmap';
COMMENT ON COLUMN public.wuwa_rebuild_log.o1_desc IS '原词条第 1 项描述';
COMMENT ON COLUMN public.wuwa_rebuild_log.o2_desc IS '原词条第 2 项描述';
COMMENT ON COLUMN public.wuwa_rebuild_log.o3_desc IS '原词条第 3 项描述';
COMMENT ON COLUMN public.wuwa_rebuild_log.o4_desc IS '原词条第 4 项描述';
COMMENT ON COLUMN public.wuwa_rebuild_log.o5_desc IS '原词条第 5 项描述';
COMMENT ON COLUMN public.wuwa_rebuild_log.new_stat1 IS '新词条第 1 项 bitmap';
COMMENT ON COLUMN public.wuwa_rebuild_log.new_stat2 IS '新词条第 2 项 bitmap';
COMMENT ON COLUMN public.wuwa_rebuild_log.new_stat3 IS '新词条第 3 项 bitmap';
COMMENT ON COLUMN public.wuwa_rebuild_log.new_stat4 IS '新词条第 4 项 bitmap';
COMMENT ON COLUMN public.wuwa_rebuild_log.new_stat5 IS '新词条第 5 项 bitmap';
COMMENT ON COLUMN public.wuwa_rebuild_log.new_stat_all IS '新词条合集 bitmap';
COMMENT ON COLUMN public.wuwa_rebuild_log.n1_desc IS '新词条第 1 项描述';
COMMENT ON COLUMN public.wuwa_rebuild_log.n2_desc IS '新词条第 2 项描述';
COMMENT ON COLUMN public.wuwa_rebuild_log.n3_desc IS '新词条第 3 项描述';
COMMENT ON COLUMN public.wuwa_rebuild_log.n4_desc IS '新词条第 4 项描述';
COMMENT ON COLUMN public.wuwa_rebuild_log.n5_desc IS '新词条第 5 项描述';
COMMENT ON COLUMN public.wuwa_rebuild_log.source_image IS '来源图片文件名或标识';
COMMENT ON COLUMN public.wuwa_rebuild_log.raw_json IS 'OCR 原始识别 JSON';
COMMENT ON COLUMN public.wuwa_rebuild_log.deleted IS '软删除标记：0 未删除，1 已删除';

ALTER TABLE public.wuwa_rebuild_log
    ADD COLUMN IF NOT EXISTS locked_count INTEGER NOT NULL DEFAULT 0;

ALTER TABLE public.wuwa_rebuild_log
    ADD COLUMN IF NOT EXISTS uploader_nickname TEXT NOT NULL DEFAULT '';

ALTER TABLE public.wuwa_rebuild_log
    ADD COLUMN IF NOT EXISTS uploader_email TEXT NOT NULL DEFAULT '';

ALTER TABLE public.wuwa_rebuild_log
    ADD COLUMN IF NOT EXISTS uploader_wechat TEXT NOT NULL DEFAULT '';

ALTER TABLE public.wuwa_rebuild_log
    ADD COLUMN IF NOT EXISTS uploader_qq TEXT NOT NULL DEFAULT '';

ALTER TABLE public.wuwa_rebuild_log
    ADD COLUMN IF NOT EXISTS request_ip TEXT NOT NULL DEFAULT '';

ALTER TABLE public.wuwa_rebuild_log
    ADD COLUMN IF NOT EXISTS uploaded_image TEXT NOT NULL DEFAULT '';

COMMENT ON COLUMN public.wuwa_rebuild_log.locked_count IS '原词条锁定数量';
COMMENT ON COLUMN public.wuwa_rebuild_log.uploader_nickname IS '上传者昵称';
COMMENT ON COLUMN public.wuwa_rebuild_log.uploader_email IS '上传者邮箱';
COMMENT ON COLUMN public.wuwa_rebuild_log.uploader_wechat IS '上传者微信';
COMMENT ON COLUMN public.wuwa_rebuild_log.uploader_qq IS '上传者 QQ';
COMMENT ON COLUMN public.wuwa_rebuild_log.request_ip IS '请求来源 IP';
COMMENT ON COLUMN public.wuwa_rebuild_log.uploaded_image IS '上传到 images 目录后的文件名';

UPDATE public.wuwa_rebuild_log
SET locked_count = (
    ((locked_bitmap >> 0) & 1) +
    ((locked_bitmap >> 1) & 1) +
    ((locked_bitmap >> 2) & 1) +
    ((locked_bitmap >> 3) & 1) +
    ((locked_bitmap >> 4) & 1)
)
WHERE locked_count = 0
  AND locked_bitmap <> 0;

CREATE INDEX IF NOT EXISTS idx_wuwa_rebuild_log_user_id_deleted
    ON public.wuwa_rebuild_log (user_id, deleted);

CREATE INDEX IF NOT EXISTS idx_wuwa_rebuild_log_deleted_created_at
    ON public.wuwa_rebuild_log (deleted, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_wuwa_rebuild_log_original_stat_all
    ON public.wuwa_rebuild_log (original_stat_all);

CREATE INDEX IF NOT EXISTS idx_wuwa_rebuild_log_new_stat_all
    ON public.wuwa_rebuild_log (new_stat_all);

COMMIT;
